"""add_soft_delete_to_products

Revision ID: 1e51dd76f687
Revises: 
Create Date: 2025-12-03 19:54:08.315070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1e51dd76f687'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    # op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    # op.drop_table('audit_logs')
    op.add_column('products', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('products', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('deleted_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_products_is_deleted'), 'products', ['is_deleted'], unique=False)
    op.create_foreign_key(None, 'products', 'users', ['deleted_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_index(op.f('ix_products_is_deleted'), table_name='products')
    op.drop_column('products', 'deleted_by_id')
    op.drop_column('products', 'deleted_at')
    op.drop_column('products', 'is_deleted')
    # op.create_table('audit_logs',
    # sa.Column('id', sa.INTEGER(), nullable=False),
    # sa.Column('user_id', sa.INTEGER(), nullable=True),
    # sa.Column('organization_id', sa.INTEGER(), nullable=False),
    # sa.Column('action', sa.VARCHAR(), nullable=False),
    # sa.Column('entity_type', sa.VARCHAR(), nullable=False),
    # sa.Column('entity_id', sa.INTEGER(), nullable=True),
    # sa.Column('details', sqlite.JSON(), nullable=True),
    # sa.Column('created_at', sa.DATETIME(), nullable=False),
    # sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    # op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    # ### end Alembic commands ###
