"""fix category unique constraint for multi-tenancy

Revision ID: 3818a7b1c460
Revises: 1e51dd76f687
Create Date: 2025-12-19 13:45:25.871143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3818a7b1c460'
down_revision: Union[str, Sequence[str], None] = '1e51dd76f687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - Fix category unique constraint for multi-tenancy."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        # Drop old global unique index on name
        batch_op.drop_index('ix_categories_name')
        # Recreate index without unique constraint
        batch_op.create_index('ix_categories_name', ['name'], unique=False)
        # Add new composite unique constraint (name + organization_id)
        batch_op.create_unique_constraint('uq_category_name_org', ['name', 'organization_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema - Revert to global unique constraint."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        # Remove composite unique constraint
        batch_op.drop_constraint('uq_category_name_org', type_='unique')
        # Recreate old global unique index
        batch_op.drop_index('ix_categories_name')
        batch_op.create_index('ix_categories_name', ['name'], unique=True)
    # ### end Alembic commands ###
